/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Florian&Lisa&Jérôme&Clément
 */
public class MenuConnexion extends javax.swing.JFrame {

    /**
     * Creates new form MenuConnexion
     */
    public MenuConnexion() {
        
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LoginBDD = new javax.swing.JTextField();
        PasswordBDD = new javax.swing.JPasswordField();
        LoginECE = new javax.swing.JTextField();
        PasswordECE = new javax.swing.JPasswordField();
        BoutonConnexion = new javax.swing.JButton();
        BoutonQuitter = new javax.swing.JButton();
        BoutonCheat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        Bienvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenue.setText("Bienvenue");
        Bienvenue.setPreferredSize(new java.awt.Dimension(336, 84));

        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 49));

        LoginBDD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginBDD.setText("LoginBDD");
        LoginBDD.setPreferredSize(new java.awt.Dimension(168, 42));
        LoginBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBDDActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBDD);

        PasswordBDD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordBDD.setText("jPasswordField1");
        jPanel1.add(PasswordBDD);

        LoginECE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginECE.setText("LoginECE");
        jPanel1.add(LoginECE);

        PasswordECE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordECE.setText("jPasswordField1");
        jPanel1.add(PasswordECE);

        BoutonConnexion.setText("Connexion");
        BoutonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConnexionActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonConnexion);

        BoutonQuitter.setText("Quitter");
        BoutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonQuitter);

        BoutonCheat.setText("Cheat");
        BoutonCheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonCheatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(BoutonCheat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BoutonCheat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBDDActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_LoginBDDActionPerformed

    private void BoutonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConnexionActionPerformed
        // TODO add your handling code here:
        String LoginECES = new String();
        String LoginBDDS = new String();
        char PasswordECEC[] = new char [30];
        char PasswordBDDC[] = new char [30];
       
        LoginBDDS = LoginBDD.getText();
        LoginECES = LoginECE.getText();
        PasswordECEC = PasswordECE.getPassword();
        PasswordBDDC = PasswordBDD.getPassword();
        String PasswordECES = new String(String.valueOf(PasswordECEC));
        String PasswordBDDS = new String(String.valueOf(PasswordBDDC));
        
        // utiliser les infos ainsi obtenues pour se connecter à implementer plus tard
        this.dispose();
        Menu_principal menu_princ = new Menu_principal(LoginECES,PasswordECES,LoginBDDS,PasswordBDDS);
        menu_princ.setVisible(true);
   
        
        
    }//GEN-LAST:event_BoutonConnexionActionPerformed

    private void BoutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonQuitterActionPerformed
        // TODO add your handling code here:
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         System.exit(0);
         
    }//GEN-LAST:event_BoutonQuitterActionPerformed

    private void BoutonCheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonCheatActionPerformed
        // TODO add your handling code here:
          this.dispose();
        Menu_principal menu_princ = new Menu_principal("ducrocq","KlrIT05A@","ducrocq-rw","KlrIT05A@");
        menu_princ.setVisible(true);
    }//GEN-LAST:event_BoutonCheatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenue;
    private javax.swing.JButton BoutonCheat;
    private javax.swing.JButton BoutonConnexion;
    private javax.swing.JButton BoutonQuitter;
    private javax.swing.JTextField LoginBDD;
    private javax.swing.JTextField LoginECE;
    private javax.swing.JPasswordField PasswordBDD;
    private javax.swing.JPasswordField PasswordECE;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
