/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Lisa
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    private  String LoginECE;
    private  String PasswordECE;
    private  String LoginBDD;
    private  String PasswordBDD;
    
    
    public Menu_principal(String LoginECE, String PasswordECE, String LoginBDD, String PasswordBDD) {
        
        this.LoginECE = LoginECE;
        this.PasswordECE = PasswordECE;
        this.LoginBDD= LoginBDD;
        this.PasswordBDD = PasswordBDD;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionHopital = new javax.swing.JLabel();
        BoutonMaj = new javax.swing.JButton();
        BoutonReporting = new javax.swing.JButton();
        BoutonQuitter = new javax.swing.JButton();
        BoutonRecherche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GestionHopital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GestionHopital.setText("Gestion d'un hôpital");
        GestionHopital.setPreferredSize(new java.awt.Dimension(168, 42));

        BoutonMaj.setText("Mise à jour");
        BoutonMaj.setActionCommand("maj");
        BoutonMaj.setMaximumSize(new java.awt.Dimension(168, 42));
        BoutonMaj.setMinimumSize(new java.awt.Dimension(168, 42));
        BoutonMaj.setPreferredSize(new java.awt.Dimension(168, 42));
        BoutonMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMajActionPerformed(evt);
            }
        });

        BoutonReporting.setText("Reporting");
        BoutonReporting.setPreferredSize(new java.awt.Dimension(168, 42));
        BoutonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonReportingActionPerformed(evt);
            }
        });

        BoutonQuitter.setText("Quitter");
        BoutonQuitter.setPreferredSize(new java.awt.Dimension(168, 42));
        BoutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonQuitterActionPerformed(evt);
            }
        });

        BoutonRecherche.setText("Bouton Recherche");
        BoutonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(GestionHopital, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonMaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonRecherche))
                .addGap(472, 472, 472))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BoutonMaj, BoutonRecherche});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(GestionHopital, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(BoutonMaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(BoutonRecherche)
                .addGap(175, 175, 175)
                .addComponent(BoutonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(BoutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BoutonMaj, BoutonRecherche});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonQuitterActionPerformed
      this.dispose();
        MenuConnexion connexion = new MenuConnexion();
    connexion.setVisible(true);
       
        
    }//GEN-LAST:event_BoutonQuitterActionPerformed

    private void BoutonReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonReportingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonReportingActionPerformed

    private void BoutonMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMajActionPerformed
        // TODO add your handling code here:
        System.out.println(this.LoginECE);
        System.out.println(this.PasswordECE);
        System.out.println(this.LoginBDD);
        System.out.println(this.PasswordBDD);
    }//GEN-LAST:event_BoutonMajActionPerformed

    private void BoutonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRechercheActionPerformed
        // TODO add your handling code here:
         this.dispose();
        MenuRecherche menu_recherche = new MenuRecherche(LoginECE,PasswordECE,LoginBDD,PasswordBDD);
        menu_recherche.setVisible(true);
    }//GEN-LAST:event_BoutonRechercheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonMaj;
    private javax.swing.JButton BoutonQuitter;
    private javax.swing.JButton BoutonRecherche;
    private javax.swing.JButton BoutonReporting;
    private javax.swing.JLabel GestionHopital;
    // End of variables declaration//GEN-END:variables
}
