/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Florian
 */
public class SousMenutri extends javax.swing.JFrame {

    /**
     * Creates new form SousMenutri
     */
    public SousMenutri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuDeroulantClass = new javax.swing.JComboBox();
        BoutonValidationClasseTri = new javax.swing.JButton();
        MenuDeroulantTri = new javax.swing.JComboBox();
        NomCheck = new javax.swing.JCheckBox();
        PrenomCheck = new javax.swing.JCheckBox();
        TelephoneCheck = new javax.swing.JCheckBox();
        AdresseCheck = new javax.swing.JCheckBox();
        NumeroCheck = new javax.swing.JCheckBox();
        MutuelleCheck = new javax.swing.JCheckBox();
        CodeCheck = new javax.swing.JCheckBox();
        NomServiceCheck = new javax.swing.JCheckBox();
        BatimentCheck = new javax.swing.JCheckBox();
        DirecteurCheck = new javax.swing.JCheckBox();
        CodeServiceCheck = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultatRequete = new javax.swing.JTextArea();
        BoutonNouvelleRecherche = new javax.swing.JButton();
        BoutonRetourRecherche = new javax.swing.JButton();
        BoutonRetourPrinc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SousMenuTri");
        jLabel1.setPreferredSize(new java.awt.Dimension(336, 84));

        MenuDeroulantClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MenuDeroulantClass.setPreferredSize(new java.awt.Dimension(414, 42));
        MenuDeroulantClass.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MenuDeroulantClassComponentAdded(evt);
            }
        });

        BoutonValidationClasseTri.setText("Ok");
        BoutonValidationClasseTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValidationClasseTriActionPerformed(evt);
            }
        });

        MenuDeroulantTri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MenuDeroulantTri.setPreferredSize(new java.awt.Dimension(414, 42));
        MenuDeroulantTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeroulantTriActionPerformed(evt);
            }
        });

        NomCheck.setText("Nom");
        NomCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        NomCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomCheckActionPerformed(evt);
            }
        });

        PrenomCheck.setText("Prenom");
        PrenomCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        PrenomCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomCheckActionPerformed(evt);
            }
        });

        TelephoneCheck.setText("Telephone");
        TelephoneCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        TelephoneCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneCheckActionPerformed(evt);
            }
        });

        AdresseCheck.setText("Adresse");
        AdresseCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        AdresseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseCheckActionPerformed(evt);
            }
        });

        NumeroCheck.setText("Numero");
        NumeroCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        NumeroCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCheckActionPerformed(evt);
            }
        });

        MutuelleCheck.setText("Mutuelle");
        MutuelleCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        MutuelleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MutuelleCheckActionPerformed(evt);
            }
        });

        CodeCheck.setText("Code");
        CodeCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        CodeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeCheckActionPerformed(evt);
            }
        });

        NomServiceCheck.setText("Nom");
        NomServiceCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        NomServiceCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomServiceCheckActionPerformed(evt);
            }
        });

        BatimentCheck.setText("Batiment");
        BatimentCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        BatimentCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatimentCheckActionPerformed(evt);
            }
        });

        DirecteurCheck.setText("Directeur");
        DirecteurCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DirecteurCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DirecteurCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        DirecteurCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecteurCheckActionPerformed(evt);
            }
        });

        CodeServiceCheck.setText("Code");
        CodeServiceCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CodeServiceCheck.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CodeServiceCheck.setPreferredSize(new java.awt.Dimension(112, 25));
        CodeServiceCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeServiceCheckActionPerformed(evt);
            }
        });

        jCheckBox12.setText("1");
        jCheckBox12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox12.setPreferredSize(new java.awt.Dimension(112, 25));
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setText("2");
        jCheckBox13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox13.setPreferredSize(new java.awt.Dimension(112, 25));
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setText("3");
        jCheckBox14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox14.setPreferredSize(new java.awt.Dimension(112, 25));
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setText("4");
        jCheckBox15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox15.setPreferredSize(new java.awt.Dimension(112, 25));
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setText("5");
        jCheckBox16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox16.setPreferredSize(new java.awt.Dimension(112, 25));
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        ResultatRequete.setColumns(20);
        ResultatRequete.setRows(5);
        jScrollPane1.setViewportView(ResultatRequete);

        BoutonNouvelleRecherche.setText("Nouvelle recherche");
        BoutonNouvelleRecherche.setPreferredSize(new java.awt.Dimension(168, 30));

        BoutonRetourRecherche.setText("Retour Menu recherche");
        BoutonRetourRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRetourRechercheActionPerformed(evt);
            }
        });

        BoutonRetourPrinc.setText("Retour menu principal");
        BoutonRetourPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRetourPrincActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(114, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MenuDeroulantClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(BoutonValidationClasseTri)
                                .addGap(49, 49, 49)
                                .addComponent(MenuDeroulantTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrenomCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TelephoneCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdresseCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumeroCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MutuelleCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomServiceCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BatimentCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DirecteurCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodeServiceCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BoutonNouvelleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(BoutonRetourRecherche)
                .addGap(7, 7, 7)
                .addComponent(BoutonRetourPrinc)
                .addGap(386, 386, 386))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AdresseCheck, BatimentCheck, CodeCheck, MutuelleCheck, NomCheck, NomServiceCheck, NumeroCheck, PrenomCheck, TelephoneCheck});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuDeroulantClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonValidationClasseTri)
                    .addComponent(MenuDeroulantTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrenomCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelephoneCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresseCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MutuelleCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomServiceCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatimentCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeServiceCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirecteurCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonNouvelleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonRetourRecherche)
                    .addComponent(BoutonRetourPrinc))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BoutonValidationClasseTri, MenuDeroulantClass, MenuDeroulantTri});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AdresseCheck, BatimentCheck, CodeCheck, MutuelleCheck, NomCheck, NomServiceCheck, NumeroCheck, PrenomCheck, TelephoneCheck});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDeroulantClassComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MenuDeroulantClassComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDeroulantClassComponentAdded

    private void MenuDeroulantTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeroulantTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDeroulantTriActionPerformed

    private void NomCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomCheckActionPerformed

    private void PrenomCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomCheckActionPerformed

    private void TelephoneCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneCheckActionPerformed

    private void AdresseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseCheckActionPerformed

    private void NumeroCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCheckActionPerformed

    private void MutuelleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MutuelleCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MutuelleCheckActionPerformed

    private void CodeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeCheckActionPerformed

    private void NomServiceCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomServiceCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomServiceCheckActionPerformed

    private void BatimentCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatimentCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BatimentCheckActionPerformed

    private void DirecteurCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecteurCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecteurCheckActionPerformed

    private void CodeServiceCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeServiceCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeServiceCheckActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void BoutonRetourRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRetourRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonRetourRechercheActionPerformed

    private void BoutonRetourPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRetourPrincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonRetourPrincActionPerformed

    private void BoutonValidationClasseTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValidationClasseTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonValidationClasseTriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SousMenutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SousMenutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SousMenutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SousMenutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SousMenutri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AdresseCheck;
    private javax.swing.JCheckBox BatimentCheck;
    private javax.swing.JButton BoutonNouvelleRecherche;
    private javax.swing.JButton BoutonRetourPrinc;
    private javax.swing.JButton BoutonRetourRecherche;
    private javax.swing.JButton BoutonValidationClasseTri;
    private javax.swing.JCheckBox CodeCheck;
    private javax.swing.JCheckBox CodeServiceCheck;
    private javax.swing.JCheckBox DirecteurCheck;
    private javax.swing.JComboBox MenuDeroulantClass;
    private javax.swing.JComboBox MenuDeroulantTri;
    private javax.swing.JCheckBox MutuelleCheck;
    private javax.swing.JCheckBox NomCheck;
    private javax.swing.JCheckBox NomServiceCheck;
    private javax.swing.JCheckBox NumeroCheck;
    private javax.swing.JCheckBox PrenomCheck;
    private javax.swing.JTextArea ResultatRequete;
    private javax.swing.JCheckBox TelephoneCheck;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
